# Generated by Django 2.2.5 on 2020-03-04 14:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
            ],
            managers=[
                ('albums', django.db.models.manager.Manager()),
            ],
        ),
    ]
