# Generated by Django 2.2.5 on 2020-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VinylCollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
