# Generated by Django 2.2.5 on 2020-03-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VinylCollection', '0002_album_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='country',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='format',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.RemoveField(
            model_name='album',
            name='released',
        ),
        migrations.RemoveField(
            model_name='album',
            name='series',
        ),
        migrations.RemoveField(
            model_name='album',
            name='style',
        ),
    ]
