# Generated by Django 2.2.5 on 2020-03-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VinylCollection', '0003_auto_20200304_1137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
            ],
        ),
    ]
