# Generated by Django 2.2.5 on 2020-03-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Focuser', '0002_auto_20200303_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eclipse',
            name='description',
        ),
    ]
