# Generated by Django 2.2.5 on 2020-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Focuser', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
