# Generated by Django 2.2.5 on 2020-03-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantPlanner', '0002_auto_20200304_0900'),
        ('plantPlanner', '0002_auto_20200304_1245'),
    ]

    operations = [
    ]
